# name of action
name: Deploy

# when action should start
on:
  pull_request:
    branches:
    - master
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# jobs of this action
jobs:
  write-to-console:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello world!'
