name: Deploy with SFTP
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: sftp://p569378.mittwaldserver.info/html/
          ftp-username: p569378
          ftp-password: ${{ secrets.FTP_PASSWORT }}
