# name of action
name: Deploy

# when action should start
on:
  push:
    branches:
      - main
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# jobs of this action
jobs:
  write-to-console:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub dir
        run: ls -la ./.?*
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -avn --exclude='.gitignore' --exclude='.git/' --exclude='.github/' --exclude='.idea/' ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/www/${{ secrets.SSH_USER }}/html/typo3/

